<?xml version="1.0"?>

<robot name="nu_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find slam_project)/urdf/nu_bot.gazebo"/>

  <!--
    Parameters
  -->

  <!-- Chassis -->
  <xacro:property name="ch_r" value="0.2"/>
  <xacro:property name="ch_l" value="0.10"/>

  <!-- Casters -->
  <xacro:property name="c_x" value="${(ch_r-c_r)}"/>
  <xacro:property name="c_y" value="0"/>
  <xacro:property name="c_z" value="${-ch_l/2}"/>
  <xacro:property name="c_r" value="${w_r+c_z-0.0001}"/>

  <!-- Wheels -->
  <xacro:property name="w_r" value="0.126"/>
  <xacro:property name="w_l" value="0.05"/>
  <xacro:property name="w_y" value="${ch_r + w_l/2 + 0.005}"/>

  <!-- Camera -->
  <xacro:property name="cam_x" value="${ch_r}"/>

  <!-- Laser sensor -->
  <xacro:property name="l_s" value="0.1"/>
  <xacro:property name="l_z" value="${ch_l/2}"/>


  <!--
    Robot
  -->
  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <!-- CHASSIS -->
  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="10.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder length="${ch_l}" radius="${ch_r}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder length="${ch_l}" radius="${ch_r}"/>
      </geometry>
    </visual>


    <!-- CASTER 1 -->
    <collision name='caster_1_collision'>
      <origin xyz="${c_x} ${c_y} ${c_z}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${c_r}"/>
      </geometry>
    </collision>

    <visual name='caster_1_visual'>
      <origin xyz="${c_x} ${c_y} ${c_z}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${c_r}"/>
      </geometry>
    </visual>

    <!-- CASTER 2 -->
    <collision name='caster_2_collision'>
      <origin xyz="-${c_x} ${c_y} ${c_z}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${c_r}"/>
      </geometry>
    </collision>

    <visual name='caster_2_visual'>
      <origin xyz="-${c_x} ${c_y} ${c_z}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${c_r}"/>
      </geometry>
    </visual>
  </link>

  <!-- RIGHT WHEEL -->
  <link name ="right_wheel">
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name="right_wheel_collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${w_l}" radius="${w_r}"/>
      </geometry>
    </collision>

    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${w_l}" radius="${w_r}"/>
      </geometry>
    </visual>
  </link>

  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="0 -${w_y} 0" rpy="0 0 0"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="900"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- LEFT WHEEL -->
  <link name ="left_wheel">
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name="left_wheel_collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${w_l}" radius="${w_r}"/>
      </geometry>
    </collision>

    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${w_l}" radius="${w_r}"/>
      </geometry>
    </visual>
  </link>

  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="0 ${w_y} 0" rpy="0 0 0"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="900"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- CAMERA -->
  <link name="camera">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>

    <collision name="camera_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <visual name="camera_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="${cam_x} 0 0" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
  </joint>

  <!-- camera rgbd frame -->
  <link name="camera_rgbd_frame"></link>
  <joint type="fixed" name="camera_rgbd_frame_joint">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <child link="camera_rgbd_frame"/>
    <parent link="camera"/>
  </joint>

  <!-- LASER RANGEFINDER -->
  <link name="hokuyo">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>

    <collision name="hokuyo_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${l_s} ${l_s} ${l_s}"/>
      </geometry>
    </collision>

    <visual name="hokuyo_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://slam_project/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${ch_r} 0 ${l_z}" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
  </joint>
</robot>
